name: try

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.16
      id: cuda-toolkit
      with:
        cuda: '12.5.0'

    - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

    - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

    - run: nvcc -V
